language: node_js
node_js:
  - 12
after_success:
  - echo 'I successfully done'
install:
- npm install -g mocha
- npm install chai
- npm install chai-http
- npm install @babel/core
- npm install @babel/register
- npm install @babel/polyfill