language: node_js
node_js:
- 12
after_success:
- echo 'I successfully done'
install:
- npm install -g mocha
- npm install chai
- npm install chai-http
- npm install @babel/core
- npm install @babel/register
- npm install @babel/polyfill
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
